### ISSUE TITLE
Convention links are old

### ISSUE THREAD

**Issue by fbaptista** [naming-convention/naming-convention-guides#18]
File: Readme.md (master / dev branch)
Links for https://github.com/naming-convention/naming-convention-guides#naming-convention-topic-list are broken.

Maybe you should use:
/tree/master/
instead of /blob/

**Comment by farbodsaraf** [comment]
Hi @fbaptista, We pushed the fix now. Can you please confirm if the issue is resolved?

**Comment by fbaptista** [comment]
yes!
